#Define variables
v1 = input ("Enter your name: ")
v2 = input ("Enter an adjective: ")
v3 = input ("Enter an adjective: ")
v4 = input ("Enter an adverb: ")
v5 = input ("Enter a food: ")
v6 = input ("Enter a different food: ")
v7 = input ("Enter a noun: ")
v8 = input ("Enter a place: ")
v9 = input ("Enter verb: ")

#Output based on variables
print (v1 + " was planning a dream vacation to " + v8 + ".")
print (v1 + " was especially looking forward to trying the local")
print ("cuisine, including " + v2 + " " + v5 + " and " + v6 + ".")
print ("")
print (v1 + " will have to practice the language " + v4 + " to")
print ("make it easier to " + v9 + " with people.")
print ("")
print (v1 + " has a long list of sights to see, including the")
print (v7 + " museum and the " + v3 + " park.")
